In [26]:
import numpy as np
import matplotlib.pylab as plt

In [27]:
def model(fi0,M0,alpha,M):
    fi=0.4*np.log(10)*(fi0)*(10**(-0.4*(M-M0)*(alpha+1)))*np.exp(-10**(-0.4*(M-M0)))
    return(fi)

In [28]:
Gc2=np.zeros(3)
def GRAD(fi0,M0,alpha,M,L):
    sigma= L * 0.1
    
    dfi0 = model(fi0,M0,alpha,M)/fi0
    dchi2_fi0 = ((model(fi0,M0,alpha,M)-L)*dfi0)/sigma
    dchi2_fi0 = np.sum(dchi2_fi0)
    
    dM0 = model(fi0,M0,alpha,M)*0.4*np.log(10)*((alpha+1)-10**(-0.4*(M-M0)))
    dchi2_M0 = ((model(fi0,M0,alpha,M)-L)*dM0)/sigma
    dchi2_M0 = np.sum(dchi2_M0)
    
    dalpha = model(fi0,M0,alpha,M)*(0.4*(M-M0)*np.log(10))
    dchi2_alpha = ((model(fi0,M0,alpha,M)-L)*fi0)/sigma
    dchi2_alpha = np.sum(dchi2_alpha) 
   
    
    Gc2[0] = dchi2_fi0
    Gc2[1] = dchi2_M0
    Gc2[2] = dchi2_alpha
    
    return (Gc2)

In [29]:
M_data=np.loadtxt('LF_Blanton2001.csv',usecols=0,delimiter=',')
L_data=np.loadtxt('LF_Blanton2001.csv',usecols=1,delimiter=',')

In [32]:
fi0_o=1.46e-2
M0_o=-20.83
alpha_o=-1.2
N=100
n=.001  

In [33]:
g0=np.zeros(3)
descent = []
g0[0] = fi0_o
g0[1] = M0_o
g0[2] = alpha_o

fi0_list = []
M0_list = []
alpha_list = []
N_list = []

for i in range(N):
    fi0_list.append(g0[0])
    M0_list.append(g0[1])
    alpha_list.append(g0[2])    
    descent.append(g0)
    N_list.append(i)
   
    G=GRAD(fi0_o,M0_o,alpha_o, M_data, L_data)
    g0 = g0 - n*G     
    print (g0)
    
    fi0_o = g0[0]
    M0_o = g0[1]
    alpha_o = g0[2]

[  0.02847179 -20.8300663   -1.19967527]
[ -0.33082701 -20.82646915  -1.21114779]
[  9.52152728 -19.6710587   -4.75015233]
[-1.23255594e+11  4.09980881e+12 -1.14218692e+07]
[-1.23255594e+11             nan -5.79415513e+10]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan na

/home/agustin/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in power
  
/home/agustin/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in power
  if __name__ == '__main__':
/home/agustin/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in multiply
  if __name__ == '__main__':
